---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: ghcr.io/codestation/drone-docker
    settings:
      repo: registry.megpoid.dev/codestation/docker-gc
      tags: latest
      registry: registry.megpoid.dev
      platforms:
        - linux/amd64
        - linux/arm64
      buildkit: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: update
    image: plugins/webhook
    settings:
      urls: http://updater:8000/apis/swarm/v1/update
      token_value:
        from_secret: updater_apikey
      template: |
        {
          "images": [
            "registry.megpoid.dev/codestation/docker-gc"
          ]
        }

trigger:
  branch:
    - master
